# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://blog.heping.tech
date_format: "ordinal"
title: Heping
subtitle: "菜鸟502的个人博客"
description: "菜鸟502的个人博客"
keywords: heping,菜鸟502,phiall502
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
repository: blog/phiall.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false
# 组件配置
components:
    share:
        enabled: false

# ---------------- #
#      Author      #
# ---------------- #
author: phiall
organization: 
organization_url: 
github_username: phiall
location: 浙江杭州
email: pingphiall@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /open-source/
#     label: 开源
  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner:
    repo:
    oauth:
        client_id:
        client_secret:
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: phiall
    repo: blog
    clientID: fcc2bf4358668929fc8b
    clientSecret: ba3e9012a73cd29f6b7f0384c840026930361e30
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id:
    adsense:
        footer: false
        sidebar: false
        content_header: true
        content_footer: false

theme: jekyll-theme-cayman